fullnameOverride: event-service

args: ['npm', 'run', 'start:prod']

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: Met@hop@SecrEtKeyS
  - name: JWT_TOKEN_EXPIRES
    value: '30'
  - name: BUNNY_SERVICE_MONGODB_URL
    value: mongodb+srv://metahop:mjC8KL3MJQZ2e9vF@metahop-cluster.ozwgg.mongodb.net/bunny
  - name: BUNNY_SERVICE_RABITMQ_URL
    value: amqp://metahop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: BUNNY_SERVICE_RABITMQ_QUEUE
    value: bunny_queue
  - name: QUIZZ_SERVICE_MONGODB_URL
    value: mongodb+srv://metahop:mjC8KL3MJQZ2e9vF@metahop-cluster.ozwgg.mongodb.net/quizz
  - name: QUIZZ_SERVICE_RABITMQ_URL
    value: amqp://metahop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: QUIZZ_SERVICE_RABITMQ_QUEUE
    value: quizz_queue
  - name: COURSE_SERVICE_MONGODB_URL
    value: mongodb+srv://metahop:mjC8KL3MJQZ2e9vF@metahop-cluster.ozwgg.mongodb.net/course
  - name: COURSE_SERVICE_RABITMQ_URL
    value: amqp://metahop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: COURSE_SERVICE_RABITMQ_QUEUE
    value: course_queue
  - name: EVENT_SERVICE_MONGODB_URL
    value: mongodb+srv://metahop:mjC8KL3MJQZ2e9vF@metahop-cluster.ozwgg.mongodb.net/event
  - name: EVENT_SERVICE_RABITMQ_URL
    value: amqp://metahop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: EVENT_SERVICE_RABITMQ_QUEUE
    value: event_queue
  - name: SHARED_SERVICE_MONGODB_URL
    value: mongodb+srv://metahop:mjC8KL3MJQZ2e9vF@metahop-cluster.ozwgg.mongodb.net/shared
  - name: SHARED_SERVICE_RABITMQ_URL
    value: amqp://metahop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: SHARED_SERVICE_RABITMQ_QUEUE
    value: shared_queue
  - name: USER_SERVICE_MONGODB_URL
    value: mongodb+srv://metahop:mjC8KL3MJQZ2e9vF@metahop-cluster.ozwgg.mongodb.net/user
  - name: USER_SERVICE_RABITMQ_URL
    value: amqp://metahop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: USER_SERVICE_RABITMQ_QUEUE
    value: user_queue
  - name: ACTIVITY_SERVICE_MONGODB_URL
    value: mongodb+srv://metahop:mjC8KL3MJQZ2e9vF@metahop-cluster.ozwgg.mongodb.net/activity
  - name: ACTIVITY_SERVICE_RABITMQ_URL
    value: amqp://metahop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: ACTIVITY_SERVICE_RABITMQ_QUEUE
    value: activity_queue
  - name: ASSET_URL
    value: https://assets.metahop.com
  - name: DEFAULT_PAGE_SIZE
    value: '20'
  - name: JWT_TOKEN_FE_SECRET
    value: Met@hop@SecrEtKeySProdSecretKey
  - name: JWT_EXPIRED_TOKEN_FE
    value: "86400"
  - name: JWT_REFRESH_TOKEN_FE_SECRET
    value: Met@hop@SecrEtKeySProdRefreshKey
  - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME_FE
    value: "2592000"

nodeAffinityPreset:
  type: "hard"

livenessProbe:
  path: /health

readinessProbe:
  path: /health
